name: Actions for CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  compile-code:
    runs-on: self-hosted

    steps:
      - name: checkout the code
        uses: actions/checkout@v4

      - name: sets up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: "21"

      - name: compile the code
        run: mvn compile

  Run-Trivy-Scan:
    runs-on: self-hosted
    needs: compile-code

    steps:
      - name: checkout the code
        uses: actions/checkout@v4

      - name: Install Trivy
        run: |
          sudo apt-get install wget gnupg
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb generic main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt update
          sudo apt install trivy -y

      - name: Run Trivy scan for source code
        run: trivy fs --format json -o fs-report.json .

      - name: Install Gitleaks
        run: sudo apt install gitleaks -y

      - name: Run Gitleaks Scan
        run: gitleaks detect source . -r gitleaks-report.json -f json

  Run-Unit-Tests:
    runs-on: self-hosted
    needs: Run-Trivy-Scan

    steps:
      - name: checkout the code
        uses: actions/checkout@v4

      - name: sets up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Run the unit tests
        run: mvn test

    
  Build-application:
    runs-on: self-hosted
    needs: Run-Unit-Tests

    steps:
      - name: checkout the code
        uses: actions/checkout@v4

      - name: sets up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Build the application
        run: mvn package

      - uses: actions/upload-artifact@v4
        with:
         name: application-artifact
         path: target/*.jar
         
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6 
        env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}

      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        with:
         pollingTimeoutSec: 600
        env:
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}

  build-and-push-to-dockerhub:
    runs-on: self-hosted
    steps:
       - uses: actions/download-artifact@v5
         with:
          path: app

       - name: Login to Docker Hub
         uses: docker/login-action@v3
         with:
           username: ${{ vars.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
      
       -  name: Set up QEMU
          uses: docker/setup-qemu-action@v3
      
       -  name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
      
       - name: Build and push
         uses: docker/build-push-action@v6
         with:
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/secondprojectgithubactions:latest