name: Actions for CI/CD Pipeline

on:
    push:
        branches:
            - main

jobs:
    compile-code:
        runs-on: self-hosted

        steps:
        - name: checkout the code    
          uses: actions/checkout@v4

        - name: sets up JDK 21
          uses: actions/setup-java@v5
          with:
            distribution: 'temurin'
            java-version: '21'

        - name: compile the code
          run: mvn compile